import{ PT }from"../types";

//仮のPTデータ
export const allPTs: PT[]=[
    {id:1, name:"田中 健太郎", specialty:"運動器", experienceYears:6, skills:["腰の痛み","膝の痛み"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。"},
    {id:2, name:"佐藤 美咲", specialty:"神経系", experienceYears:4, skills:["脳卒中後遺症","パーキンソン病"], photo: "https://i.pravatar.cc/150?u=2", message: "痛みを取り除くだけでなく、再発しない身体作りをサポートします。"},
    {id:3, name:"鈴木 大輔", specialty:"呼吸器", experienceYears:8, skills:["COPD","喘息"], photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:4, name:"高橋 由美子", specialty:"小児", experienceYears:3, skills:["発達障害","筋ジストロフィー"],photo: "https://i.pravatar.cc/150?u=3", message: "患者様の『また歩きたい』という気持ちに寄り添ったリハビリを心がけています。"},
    {id:5, name:"伊藤 翔太", specialty:"運動器", experienceYears:5, skills:["肩の痛み","膝の痛み"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。"},
    {id:6, name:"渡辺 彩香", specialty:"神経系", experienceYears:7, skills:["脳卒中後遺症","多発性硬化症"], photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:7, name:"山本 裕子", specialty:"呼吸器", experienceYears:2, skills:["肺炎","COPD"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:8, name:"中村 亮太", specialty:"小児", experienceYears:9, skills:["発達障害","脳性麻痺"], photo: "https://i.pravatar.cc/150?u=3", message: "最新のエビデンスに基づき、効率的なトレーニングメニューを提案します。"},
    {id:9, name:"小林 真奈美", specialty:"運動器", experienceYears:4, skills:["腰の痛み","肩の痛み"], photo: "https://i.pravatar.cc/150?u=3", message: "患者様の『また歩きたい』という気持ちに寄り添ったリハビリを心がけています。"},
    {id:10, name:"加藤 大輝", specialty:"神経系", experienceYears:6, skills:["パーキンソン病","脳卒中後遺症"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:11, name:"吉田 奈々", specialty:"呼吸器", experienceYears:5, skills:["喘息","COPD"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:12, name:"佐々木 翔", specialty:"小児", experienceYears:3, skills:["筋ジストロフィー","発達障害"], photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:13, name:"山田 花子", specialty:"運動器", experienceYears:7, skills:["膝の痛み","腰の痛み"], photo: "https://i.pravatar.cc/150?u=3", message: "最新のエビデンスに基づき、効率的なトレーニングメニューを提案します。"},
    {id:14, name:"松本 健一", specialty:"神経系", experienceYears:4, skills:["多発性硬化症","脳卒中後遺症"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。"},
    {id:15, name:"井上 美咲", specialty:"呼吸器", experienceYears:8, skills:["COPD","肺炎"], photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:16, name:"木村 大輔", specialty:"小児", experienceYears:2, skills:["脳性麻痺","発達障害"], photo: "https://i.pravatar.cc/150?u=3", message: "長年の臨床経験を活かし、難しい症例にも粘り強く向き合います"},
    {id:17, name:"林 由美子", specialty:"運動器", experienceYears:5, skills:["肩の痛み","膝の痛み"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。"},
    {id:18, name:"清水 翔太", specialty:"神経系", experienceYears:6, skills:["脳卒中後遺症","パーキンソン病"],photo: "https://i.pravatar.cc/150?u=3", message: "患者様の『また歩きたい』という気持ちに寄り添ったリハビリを心がけています。"},
    {id:19, name:"斎藤 彩香", specialty:"呼吸器", experienceYears:3, skills:["喘息","COPD"], photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:20, name:"遠藤 裕子", specialty:"小児", experienceYears:9, skills:["発達障害","筋ジストロフィー"], photo: "https://i.pravatar.cc/150?u=3", message: "長年の臨床経験を活かし、難しい症例にも粘り強く向き合います"},
    {id:21, name:"松村 邦洋", specialty: "中枢神経", experienceYears: 1, skills: ["脳梗塞後", "麻痺改善", "歩行リハビリ"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:22, name:"西村 雅彦", specialty: "中枢神経", experienceYears: 18, skills: ["パーキンソン病", "神経難病", "姿勢調整"], photo: "https://i.pravatar.cc/150?u=3", message: "痛みを取り除くだけでなく、再発しない身体作りをサポートします。" },
    {id:23, name:"阿部 寛", specialty: "運動器", experienceYears: 12, skills: ["膝の痛み", "腰痛", "股関節痛"], photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:24, name:"森田 剛", specialty: "運動器", experienceYears: 4, skills: ["捻挫", "肉離れ", "スポーツ外傷"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:25, name:"藤田 恵子", specialty: "運動器", experienceYears: 25, skills: ["慢性腰痛", "五十肩", "変形性膝関節症"], photo: "https://i.pravatar.cc/150?u=3", message: "最新のエビデンスに基づき、効率的なトレーニングメニューを提案します。" },
    {id:26, name:"竹内 涼真", specialty: "中枢神経", experienceYears: 7, skills: ["脳卒中後", "リハビリテーション", "運動療法"] , photo: "https://i.pravatar.cc/150?u=3", message: "痛みを取り除くだけでなく、再発しない身体作りをサポートします。"},
    {id:27, name:"吉岡 美穂", specialty: "運動器", experienceYears: 10, skills: ["スポーツリハビリ", "筋力強化", "関節可動域改善"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:28, name:"佐野 史郎", specialty: "中枢神経", experienceYears: 15, skills: ["多発性硬化症", "神経リハビリ", "バランス訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます" },
    {id:29, name:"長谷川 潤", specialty: "運動器", experienceYears: 3, skills: ["肩こり", "腰痛", "姿勢改善"],photo: "https://i.pravatar.cc/150?u=3", message: "長年の臨床経験を活かし、難しい症例にも粘り強く向き合います"},
    {id:30, name:"堀北 真希", specialty: "中枢神経", experienceYears: 20, skills: ["脳性麻痺", "発達障害", "歩行訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" }, 
    {id:31, name:"市川 海老蔵", specialty: "運動器", experienceYears: 14, skills: ["スポーツ障害", "リハビリテーション", "筋力回復"] ,photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:32, name:"寺田 海", specialty: "中枢神経", experienceYears: 9, skills: ["脳卒中リハビリ", "神経回復", "運動機能改善"],photo: "https://i.pravatar.cc/150?u=3", message: "痛みを取り除くだけでなく、再発しない身体作りをサポートします。"},
    {id:33, name:"篠原 陽介", specialty: "運動器", experienceYears: 11, skills: ["関節痛", "筋肉痛", "スポーツパフォーマンス向上"],photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:34, name:"平本 一郎", specialty: "中枢神経", experienceYears: 6, skills: ["パーキンソン病リハビリ", "神経機能改善", "バランス訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "最新のエビデンスに基づき、効率的なトレーニングメニューを提案します。" },
    {id:35, name:"野田 はじめ", specialty: "運動器", experienceYears: 8, skills: ["スポーツリハビリテーション", "筋力強化", "関節可動域改善"],photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます" },
    {id:36, name:"松元 謙太", specialty: "中枢神経", experienceYears: 13, skills: ["多発性硬化症リハビリ", "神経回復", "歩行訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:37, name:"大坪 博子", specialty: "運動器", experienceYears: 5, skills: ["慢性腰痛", "肩こり", "姿勢改善"],photo: "https://i.pravatar.cc/150?u=3", message: "長年の臨床経験を活かし、難しい症例にも粘り強く向き合います" },
    {id:38, name:"北川 景子", specialty: "中枢神経", experienceYears: 17, skills: ["脳性麻痺リハビリ", "発達障害支援", "運動機能改善"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:39, name:"石川 大勢", specialty: "運動器", experienceYears: 22, skills: ["スポーツ障害リハビリ", "筋力回復", "関節可動域改善"],photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:40, name:"岩切 悠斗", specialty: "中枢神経", experienceYears: 19, skills: ["脳卒中リハビリテーション", "神経機能改善", "バランス訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます"},
    {id:41, name:"山田 海斗", specialty: "運動器", experienceYears: 2, skills: ["肩の痛み", "腰痛", "スポーツリハビリ"], photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。"},
    {id:42, name:"志岐 沙知", specialty: "中枢神経", experienceYears: 16, skills: ["パーキンソン病リハビリ", "神経回復", "歩行訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "最新のエビデンスに基づき、効率的なトレーニングメニューを提案します。" },
    {id:43, name:"新垣 結衣", specialty: "運動器", experienceYears: 21, skills: ["慢性腰痛", "五十肩", "姿勢改善"] ,photo: "https://i.pravatar.cc/150?u=3", message: "長年の臨床経験を活かし、難しい症例にも粘り強く向き合います"},
    {id:44, name:"松坂 桃李", specialty: "中枢神経", experienceYears: 12, skills: ["多発性硬化症リハビリ", "神経機能改善", "バランス訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:45, name:"高橋 ありさ", specialty: "運動器", experienceYears: 4, skills: ["スポーツリハビリ", "筋力強化", "関節可動域改善"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:46, name:"山本 春和", specialty: "中枢神経", experienceYears: 3, skills: ["脳卒中後遺症", "神経回復", "運動機能改善"],photo: "https://i.pravatar.cc/150?u=3", message: "丁寧なカウンセリングで、生活スタイルに合わせた改善策を見つけます" },
    {id:47, name:"中村 美咲", specialty: "運動器", experienceYears: 15, skills: ["関節痛", "筋肉痛", "スポーツパフォーマンス向上"],photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:48, name:"都築 花", specialty: "中枢神経", experienceYears: 7, skills: ["パーキンソン病リハビリ", "神経機能改善", "バランス訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
    {id:49, name:"藤原 真也", specialty: "運動器", experienceYears: 9, skills: ["スポーツリハビリテーション", "筋力強化", "関節可動域改善"],photo: "https://i.pravatar.cc/150?u=1", message: "スポーツ整形外科での勤務経験が豊富です。" },
    {id:50, name:"加藤 翔太郎", specialty: "中枢神経", experienceYears: 1, skills: ["多発性硬化症リハビリ", "神経回復", "歩行訓練"],photo: "https://i.pravatar.cc/150?u=3", message: "在宅リハビリの経験を活かし、生活に寄り添います。" },
];


    
