const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 福岡・博多リハビリDX：シードデータの投入を開始します...');

  // 1. 既存データのクリーンアップ（リセット時の二重登録防止）
  await prisma.therapist.deleteMany({});
  await prisma.user.deleteMany({});

  // 2. 「初期メンバー」として表示される、実名感のあるデータ
  const fixedTherapists = [
    {
      id: 'pt_fixed_1',
      name: '田中 健太郎',
      email: 'tanaka@example.com',
      specialty: '運動器（膝・腰）',
      experience: 12,
      message: '病院でのリハビリ経験を活かし、ご自宅での生活に合わせたトレーニングを提案します。',
      photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=200&h=200&fit=crop',
      lat: 33.5897, lng: 130.4207, // 博多駅
      rating: 4.9, price: 6500,
    },
    {
      id: 'pt_fixed_2',
      name: '佐藤 雅也',
      email: 'sato@example.com',
      specialty: '脳血管・脳卒中',
      experience: 8,
      message: '麻痺があっても「やりたいこと」ができる体づくりを、理学療法の視点でサポートします。',
      photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=200&h=200&fit=crop',
      lat: 33.5912, lng: 130.4215,
      rating: 4.7, price: 5500,
    },
    {
      id: 'pt_fixed_3',
      name: '高橋 瞳',
      email: 'takahashi@example.com',
      specialty: 'ウィメンズヘルス',
      experience: 6,
      message: '産前産後の腰痛や、女性特有の体の悩みに対して丁寧にケアします。',
      photo: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=200&h=200&fit=crop',
      lat: 33.5850, lng: 130.4100, // 天神
      rating: 4.8, price: 7000,
    }
  ];

  // 3. 残りのメンバーを自動生成（合計で15名程度にして「寂しくない」状態を作る）
  const specialties = ["運動器", "中枢神経", "呼吸器", "小児", "認知症予防"];
  const autoGeneratedCount = 12;

  const dynamicTherapists = Array.from({ length: autoGeneratedCount }).map((_, i) => {
    const id = i + 1;
    return {
      id: `pt_auto_${id}`,
      name: `療法士 ${id}号`,
      email: `auto_pt${id}@example.com`,
      specialty: specialties[i % specialties.length],
      experience: 3 + (i % 12),
      message: `${specialties[i % specialties.length]}の専門知識を活かし、質の高いリハビリを提供します。`,
      photo: `https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=200&h=200&fit=crop`,
      lat: 33.5897 + (Math.random() - 0.5) * 0.04,
      lng: 130.4207 + (Math.random() - 0.5) * 0.04,
      rating: parseFloat((4.0 + Math.random() * 1.0).toFixed(1)),
      price: 5000 + (Math.floor(Math.random() * 4) * 500),
    };
  });

  // 4. 全員をデータベースに保存
  const allTherapists = [...fixedTherapists, ...dynamicTherapists];
  
  for (const pt of allTherapists) {
    await prisma.therapist.create({
      data: {
        ...pt,
        walletBalance: 0,
      },
    });
  }

  // 5. テスト用ユーザー作成
  await prisma.user.create({
    data: {
      id: 'user_fukuoka_test',
      name: '福岡 太郎',
      email: 'user@example.com',
      symptom: '膝の術後のリハビリを希望しています',
    },
  });

  console.log(`\n-----------------------------------------`);
  console.log(`✅ 成功: 合計 ${allTherapists.length} 名を博多エリアに配置しました。`);
  console.log(`   (内訳: 初期メンバー3名 + 自動生成${autoGeneratedCount}名)`);
  console.log(`-----------------------------------------\n`);
}

main()
  .catch((e) => {
    console.error('❌ シードエラー:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });